version: '3'
services:
  frontend:
    build: ./frontend
    container_name: handwrite_recognition_nginx
    ports:
      - "80:80"
  backend:
    build: ./backend
    container_name: handwrite_recognition_web
    ports:
      - "8080:8080"
  ml:
    build: ./ml
    container_name: handwrite_recognition_ml
    environment:
      - TESSDATA_PREFIX=/ml/share/tessdata
    ports:
      - "1234:1234"
  queue:
    image: rabbitmq
    container_name: handwrite_recognition_mq
    ports:
      - "5672:5672"
  react_frontend:
    build: ./react-frontend
    container_name: handwrite_recognition_react
    ports:
      - "3000:3000"
  psql:
    image: postgres
    container_name: handwrite_recognition_psql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=somepassword
