services:
  frontend:
    build: ./frontend
    container_name: handwrite_recognition_nginx
    ports:
      - "80:80"
  backend:
    build: ./backend
    container_name: handwrite_recognition_web
    ports:
      - "8080:8080"
  ml:
    build: ./ml
    container_name: handwrite_recognition_ml
    ports:
      - "1234:1234"
  queue:
    image: rabbitmq
    container_name: handwrite_recognition_mq
    ports:
      - "5672:5672"
